// Generated by Wrangler by running `wrangler types`

interface Env {
	FORGE_VERSIONS: KVNamespace;
	FORGE_MAVEN_URL: "https://files.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml";
	FORGE_PROMO_URL: "https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json";
}
